[2025-09-20T16:04:43.562+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T16:03:21.323066+00:00 [queued]>
[2025-09-20T16:04:43.580+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T16:03:21.323066+00:00 [queued]>
[2025-09-20T16:04:43.581+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-20T16:04:43.608+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-20 16:03:21.323066+00:00
[2025-09-20T16:04:43.615+0000] {standard_task_runner.py:60} INFO - Started process 5582 to run task
[2025-09-20T16:04:43.622+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sap_elt_pipeline', 'run_dbt_models', 'manual__2025-09-20T16:03:21.323066+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/sap_etl_pipeline.py', '--cfg-path', '/tmp/tmp7w98i_ni']
[2025-09-20T16:04:43.626+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask run_dbt_models
[2025-09-20T16:04:43.703+0000] {task_command.py:423} INFO - Running <TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T16:03:21.323066+00:00 [running]> on host ca9121c9acbc
[2025-09-20T16:04:43.916+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sap_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T16:03:21.323066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T16:03:21.323066+00:00'
[2025-09-20T16:04:43.920+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-20T16:04:43.923+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt --profiles-dir /opt/***/dbt']
[2025-09-20T16:04:43.945+0000] {subprocess.py:86} INFO - Output:
[2025-09-20T16:04:50.832+0000] {subprocess.py:93} INFO - [0m16:04:50  Running with dbt=1.9.0-b2
[2025-09-20T16:04:50.843+0000] {subprocess.py:93} INFO - [0m16:04:50  [[33mWARNING[0m]: Deprecated functionality
[2025-09-20T16:04:50.845+0000] {subprocess.py:93} INFO - 
[2025-09-20T16:04:50.848+0000] {subprocess.py:93} INFO - User config should be moved from the 'config' key in profiles.yml to the 'flags' key in dbt_project.yml.
[2025-09-20T16:04:54.655+0000] {subprocess.py:93} INFO - [0m16:04:54  Registered adapter: snowflake=1.8.0
[2025-09-20T16:04:56.145+0000] {subprocess.py:93} INFO - [0m16:04:56  Found 5 models, 5 sources, 453 macros
[2025-09-20T16:04:56.152+0000] {subprocess.py:93} INFO - [0m16:04:56
[2025-09-20T16:04:56.156+0000] {subprocess.py:93} INFO - [0m16:04:56  Concurrency: 4 threads (target='dev')
[2025-09-20T16:04:56.157+0000] {subprocess.py:93} INFO - [0m16:04:56
[2025-09-20T16:05:01.065+0000] {subprocess.py:93} INFO - [0m16:05:01
[2025-09-20T16:05:01.070+0000] {subprocess.py:93} INFO - [0m16:05:01  Finished running  in 0 hours 0 minutes and 4.90 seconds (4.90s).
[2025-09-20T16:05:01.076+0000] {subprocess.py:93} INFO - [0m16:05:01  Encountered an error:
[2025-09-20T16:05:01.079+0000] {subprocess.py:93} INFO - Database Error
[2025-09-20T16:05:01.081+0000] {subprocess.py:93} INFO -   003001 (42501): SQL access control error:
[2025-09-20T16:05:01.084+0000] {subprocess.py:93} INFO -   Insufficient privileges to operate on database 'SAP_ANALYTICS_DB'.
[2025-09-20T16:05:01.817+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-20T16:05:01.842+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-20T16:05:01.850+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sap_elt_pipeline, task_id=run_dbt_models, execution_date=20250920T160321, start_date=20250920T160443, end_date=20250920T160501
[2025-09-20T16:05:01.894+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 5582)
[2025-09-20T16:05:01.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-20T16:05:01.992+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
