[2025-09-12T18:57:19.826+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T18:56:12.430819+00:00 [queued]>
[2025-09-12T18:57:19.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T18:56:12.430819+00:00 [queued]>
[2025-09-12T18:57:19.839+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-12T18:57:19.869+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-12 18:56:12.430819+00:00
[2025-09-12T18:57:19.878+0000] {standard_task_runner.py:60} INFO - Started process 8752 to run task
[2025-09-12T18:57:19.884+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sap_elt_pipeline', 'run_dbt_models', 'manual__2025-09-12T18:56:12.430819+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/sap_etl_pipeline.py', '--cfg-path', '/tmp/tmpbcxm6yl8']
[2025-09-12T18:57:19.889+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask run_dbt_models
[2025-09-12T18:57:19.949+0000] {task_command.py:423} INFO - Running <TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T18:56:12.430819+00:00 [running]> on host f99cf7ca5f05
[2025-09-12T18:57:20.064+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sap_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T18:56:12.430819+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T18:56:12.430819+00:00'
[2025-09-12T18:57:20.067+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T18:57:20.069+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt --profiles-dir /opt/***/dbt']
[2025-09-12T18:57:20.080+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T18:57:22.465+0000] {subprocess.py:93} INFO - [0m18:57:22  Running with dbt=1.9.0-b2
[2025-09-12T18:57:22.479+0000] {subprocess.py:93} INFO - [0m18:57:22  [[33mWARNING[0m]: Deprecated functionality
[2025-09-12T18:57:22.479+0000] {subprocess.py:93} INFO - 
[2025-09-12T18:57:22.480+0000] {subprocess.py:93} INFO - User config should be moved from the 'config' key in profiles.yml to the 'flags' key in dbt_project.yml.
[2025-09-12T18:57:24.226+0000] {subprocess.py:93} INFO - [0m18:57:24  Registered adapter: snowflake=1.8.0
[2025-09-12T18:57:24.452+0000] {subprocess.py:93} INFO - [0m18:57:24  Unable to do partial parsing because a project config has changed
[2025-09-12T18:57:28.384+0000] {subprocess.py:93} INFO - [0m18:57:28  Found 5 models, 5 sources, 453 macros
[2025-09-12T18:57:28.387+0000] {subprocess.py:93} INFO - [0m18:57:28
[2025-09-12T18:57:28.388+0000] {subprocess.py:93} INFO - [0m18:57:28  Concurrency: 4 threads (target='dev')
[2025-09-12T18:57:28.389+0000] {subprocess.py:93} INFO - [0m18:57:28
[2025-09-12T18:57:32.225+0000] {subprocess.py:93} INFO - [0m18:57:32
[2025-09-12T18:57:32.230+0000] {subprocess.py:93} INFO - [0m18:57:32  Finished running  in 0 hours 0 minutes and 3.83 seconds (3.83s).
[2025-09-12T18:57:32.234+0000] {subprocess.py:93} INFO - [0m18:57:32  Encountered an error:
[2025-09-12T18:57:32.235+0000] {subprocess.py:93} INFO - Database Error
[2025-09-12T18:57:32.236+0000] {subprocess.py:93} INFO -   003001 (42501): SQL access control error:
[2025-09-12T18:57:32.236+0000] {subprocess.py:93} INFO -   Insufficient privileges to operate on database 'SAP_ANALYTICS_DB'.
[2025-09-12T18:57:32.864+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T18:57:32.875+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T18:57:32.881+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sap_elt_pipeline, task_id=run_dbt_models, execution_date=20250912T185612, start_date=20250912T185719, end_date=20250912T185732
[2025-09-12T18:57:32.900+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 8752)
[2025-09-12T18:57:32.941+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-12T18:57:32.970+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
