[2025-09-20T15:40:25.504+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T15:39:00.949585+00:00 [queued]>
[2025-09-20T15:40:25.563+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T15:39:00.949585+00:00 [queued]>
[2025-09-20T15:40:25.567+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-20T15:40:25.646+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-20 15:39:00.949585+00:00
[2025-09-20T15:40:25.661+0000] {standard_task_runner.py:60} INFO - Started process 4407 to run task
[2025-09-20T15:40:25.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sap_elt_pipeline', 'run_dbt_models', 'manual__2025-09-20T15:39:00.949585+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/sap_etl_pipeline.py', '--cfg-path', '/tmp/tmpp5_5tyyy']
[2025-09-20T15:40:25.686+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask run_dbt_models
[2025-09-20T15:40:25.879+0000] {task_command.py:423} INFO - Running <TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-20T15:39:00.949585+00:00 [running]> on host ca9121c9acbc
[2025-09-20T15:40:26.269+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sap_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T15:39:00.949585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T15:39:00.949585+00:00'
[2025-09-20T15:40:26.274+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-20T15:40:26.281+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt --profiles-dir /opt/***/dbt']
[2025-09-20T15:40:26.319+0000] {subprocess.py:86} INFO - Output:
[2025-09-20T15:40:34.157+0000] {subprocess.py:93} INFO - [0m15:40:34  Running with dbt=1.9.0-b2
[2025-09-20T15:40:34.182+0000] {subprocess.py:93} INFO - [0m15:40:34  [[33mWARNING[0m]: Deprecated functionality
[2025-09-20T15:40:34.185+0000] {subprocess.py:93} INFO - 
[2025-09-20T15:40:34.187+0000] {subprocess.py:93} INFO - User config should be moved from the 'config' key in profiles.yml to the 'flags' key in dbt_project.yml.
[2025-09-20T15:40:38.036+0000] {subprocess.py:93} INFO - [0m15:40:38  Registered adapter: snowflake=1.8.0
[2025-09-20T15:40:42.364+0000] {subprocess.py:93} INFO - [0m15:40:42  Found 5 models, 5 sources, 453 macros
[2025-09-20T15:40:42.375+0000] {subprocess.py:93} INFO - [0m15:40:42
[2025-09-20T15:40:42.378+0000] {subprocess.py:93} INFO - [0m15:40:42  Concurrency: 4 threads (target='dev')
[2025-09-20T15:40:42.381+0000] {subprocess.py:93} INFO - [0m15:40:42
[2025-09-20T15:40:47.239+0000] {subprocess.py:93} INFO - [0m15:40:47
[2025-09-20T15:40:47.242+0000] {subprocess.py:93} INFO - [0m15:40:47  Finished running  in 0 hours 0 minutes and 4.86 seconds (4.86s).
[2025-09-20T15:40:47.247+0000] {subprocess.py:93} INFO - [0m15:40:47  Encountered an error:
[2025-09-20T15:40:47.248+0000] {subprocess.py:93} INFO - Database Error
[2025-09-20T15:40:47.250+0000] {subprocess.py:93} INFO -   003001 (42501): SQL access control error:
[2025-09-20T15:40:47.251+0000] {subprocess.py:93} INFO -   Insufficient privileges to operate on database 'SAP_ANALYTICS_DB'.
[2025-09-20T15:40:47.947+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-20T15:40:47.986+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-20T15:40:48.001+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sap_elt_pipeline, task_id=run_dbt_models, execution_date=20250920T153900, start_date=20250920T154025, end_date=20250920T154047
[2025-09-20T15:40:48.042+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 4407)
[2025-09-20T15:40:48.086+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-20T15:40:48.149+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
